version: 2

models:
- name: finance_campaigns_day
  tests:
    - unique: 
        column_name: date_date
        
- name: int_campaigns_day
  tests:
      - unique:
          column_name: date_date
  columns:
    - name: date_date
      tests:
        - not_null
    - name: ads_cost
      tests:
        - not_null
      
- name: int_sales_margin
  tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"

sources:
  - name: raw
    schema: gwz_dbt_dataset
    description: greenweez raw data source
    tables:
      - name: adwords
        identifier: raw_gz_adwords
        tests:
          - unique:
              column_name: "(date_date || '-' || paid_source || '-' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        tests:
          - unique:
              column_name: "(date_date || '-' || paid_source || '-' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        tests:
          - unique:
              column_name: "(date_date || '-' || paid_source || '-' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        tests:
          - unique:
              column_name: "(date_date || '-' || paid_source || '-' || campaign_key)"
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row for each products_id in each order_id
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        freshness: 
          warn_after:
            count: 90
            period: day
        loaded_at_field: CAST(date_date as TIMESTAMP)
      - name: product
        identifier: raw_gz_product
        description: list of products sold by greeweez / we have one row per products_id and the purchase_price
        tests:
          - unique:
              column_name: products_id
      - name: ship
        identifier: raw_gz_ship
        description: list of orders with shipping fee, ship cost and log cost
        tests:
          - unique:
              column_name: orders_id